#!/bin/bash -eu

port="$(modelctl get http.port)"
host="$(modelctl get http.host)"
model_name=$("$SNAP_NAME" model --format=json | jq -r '.name')
extra_args=()

verbose="$(modelctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--log_level DEBUG)
fi

set -x
exec ovms \
  --rest_port "$port" \
  --rest_bind_address "$host" \
  --model_name "$model_name" \
  --model_path "$MODEL_PATH" \
  --task text_generation \
  --target_device CPU \
  "${extra_args[@]}" \
  "$@"
